### ISSUE TITLE
Fix runtime invocation

### ISSUE THREAD

**Issue by wrznr** [OCR-D/ocrd_olena#3]
Current master does not work:
```console
(env) ~/Documents/Work/OCR-D/tests/dresden$ ocrd-olena-binarize -I DESKEW_OCROPY -O BIN -m mets.xml -p <(echo '{"impl": "kim"}')
17:34:42.973 INFO ocrd.workspace - Saving mets '/home/Documents/Work/OCR-D/tests/dresden/mets.xml'
...
Error: Invalid command!
```
Also with
```console
env) ~/Documents/Work/OCR-D/tests/dresden$ ocrd-olena-binarize -I DESKEW_OCROPY -O BIN -m mets.xml -p <(echo '{"impl": "sauvola-ms-split"}')
17:35:43.683 INFO ocrd.workspace - Saving mets '/home/Documents/Work/OCR-D/tests/dresden/mets.xml'
...
/home/Documents/Work/OCR-D/ocrd_olena/local/bin/scribo-cli: 143: /home/Documents/Work/OCR-D/ocrd_olena/local/bin/scribo-cli: /home/Documents/Work/OCR-D/ocrd_olena/local/libexec/scribo/sauvola_ms_split: not found
```

**Comment by wrznr** [comment]
@bertsky Any ideas?

**Comment by bertsky** [comment]
> Any ideas?

@wrznr sure! This cannot work as long as core's CLI does not expose API to target `AlternativeImage` in PAGE-XML. (We do not even have an OOP extension in bashlib yet.)

In the current state, you can only operate on images (not PAGE) as input file grp (e.g. `OCR-D-IMG`). 

For my own purposes (getting olena binarization on the page level for some existing PAGE-XML), I wrote a little bash script (as a OCR-D processor wrapped with core's bashlib) that simply uses `sed` to replace the `imageFilename` with the output path of a previous ocrd-olena-binarize. So that's a messy hack, but it does the trick.

I could generalize this to do the actual binarization as well. This could then be used in your case, if your `DESKEW_OCROPY` does already create an image file, too. It would be called like this:

```sh
ocrd-olena-binarize-page -m mets.xml -I DESKEW_OCROPY,OCR-D-IMG-DESKEW -O BIN,OCR-D-IMG-BIN -p <(echo '{"impl": "sauvola-ms-split"}')
```

What do you think?

**Comment by bertsky** [comment]
So this relates to OCR-D/core#264

**Comment by wrznr** [comment]
@bertsky My bad. Should have investigated the issue more thoroughly. I think your proposal is highly reasonable.
