### ISSUE TITLE
Overwrite existing olena archive when unconditional make is used

### ISSUE THREAD

**Issue by wrznr** [OCR-D/ocrd_olena#7]
`wget`  does not overwrite by default.

**Comment by kba** [comment]
Unconditional make is a bad idea most of the time.

How about

```make
olena-clean:
    rm -rf $(OLENA_DIR).tar.gz $(OLENA_DIR)
```

and `make olena-clean olena-build` to redownload? But why? IIRC building took ages

**Comment by wrznr** [comment]
> But why?

Dependencies are not checked in order to trigger a rebuild. If I fix let's say my boost installation only a re-download ensures reconfiguring.

**Comment by bertsky** [comment]
I am trying to fully understand this request. 

First of all: yes, `wget` should be used in a different way here – either with `-N` (which refuses to re-download if a file of that name exists locally and is already newer than on the server) or with `-nc` (which refuses to re-download if a file of that name exists locally). 

But to be clear: with the current build configuration, this would still _not_ prevent re-building when `build-olena` is requested, only re-downloading and re-patching. That's because `build-olena` is _phony_ and its recipe unconditionally runs `configure`, invalidating the previous build.

However, this does not mean that the targets `deps`, `install` or `test` would necessarily cause a rebuild: Their dependency on `build-olena` is not explicit, but rather triggered via recursive make if `scribo-cli` cannot be run successfully.

So it is only the latter case that you are trying to repair here, right? The previous build did not run through completely, but we want the next try to build incrementally?

Your last statement indicates another, contradictory use-case though. If my Boost installation were defunct, then configure would return with error, and no (long-aged) build would ensue to begin with. If I then fixed it and tried `build-olena` again, it would _still_ not re-download and re-patch (because the tarball does not depend on anything and already exists), just unconditionally re-configure and eventually build – exactly what you already wanted!

I say both use-cases are contradictory, because incremental make requires to always leave the build tree, regardless of failures, whereas unconditional reconfiguration destroys the build tree.

**Comment by bertsky** [comment]
@wrznr I believe you will find [this](https://github.com/OCR-D/ocrd_olena/pull/10/commits/2bc6a45b36219b43e47263ec845bb03435425961) to be a good approximation to a solution. Can we close?
